config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "home#index"

  resources :todo

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        if user_signed_in?
            redirect_to :controller => 'todo', :action => 'index'
        end
    end
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController

    def index
        @todos = Todo.where(done: false)
        @todone = Todo.where(done: true)
    end

    def show
        @todo = Todo.find(params[:id])
    end

    def new
        @todo = Todo.new
    end

    def todo_params
        params.require(:todo).permit(:name, :description, :done)
    end

    def create
        @todo = Todo.new(todo_params)

        if @todo.save
            redirect_to todo_index_path, success: 'Your todo has been created with success!'
        else
            render "new"
        end
    end

    def update
        @todo = Todo.find(params[:id])

        if @todo.update_attribute(:done, true)
            redirect_to todo_index_path, notice: 'Your todo has been set to done'
        else
            redirect_to todo_index_path, notice: 'Your todo has not been marked has done'
        end
    end

    def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy

        redirect_to todo_index_path, notice: 'Your todo has been removed with success!'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for(flash_type)
          { success: 'alert-success',
            error: 'alert-error',
            alert: 'alert-block',
            notice: 'alert-info'
          }[flash_type.to_sym]
    end

    def flash_messages(opts = {})
        flash.each do |msg_type, message|
            concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
            concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
            concat message
        end)
        end
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header role="banner" id="header">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">To-do app</a>
            </div>
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/todo">To-do</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                    <li>
                        <%= link_to destroy_user_session_path, :method => :delete  do %>
                            <span class="glyphicon glyphicon-log-out"></span> Sign out
                        <% end %>
                    </li>
                <% else %>
                    <li>
                        <%= link_to new_user_registration_path do %>
                            <span class="glyphicon glyphicon-user"></span> Sign up
                        <% end %>
                    </li>
                    <li>
                        <%= link_to new_user_session_path do %>
                            <span class="glyphicon glyphicon-log-in"></span> Sign in
                        <% end %>
                    </li>
                <% end %>
                <ul>
            </div>
          </div>
        </nav>
    </header>

    <div class="container">

        <%= flash_messages %>

        <%= yield %>

    </div>

    <footer id="footer">
      <div class="container">
        <p class="text-muted">
            Henrotte Simon - 2014
        </p>
      </div>
    </footer>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/todo/index.html.erb
<div class="row">
    <h1 class="col-xs-10 col-md-10 main-title">Todos items</h1>
    <p class="col-xs-2 col-md-2">
        <%= link_to "Add new todo", new_todo_path, :class => "btn btn-primary btn-block" %>
    </p>
</div>
<h2>To do</h2>
<% if @todos.blank? %>
    <p>You have no to-do for the moment</p>
<% else %>
    <ul>
        <% @todos.each do |t| %>
            <li>
                <%= link_to t.name, todo_path(t.id) %>
                <small><%= link_to "Mark as done", todo_path(t), :method => :put %></small>
            </li>
        <% end %>
    </ul>
<% end %>

<h2>Done</h2>
<% if @todone.blank? %>
    <p>You have no to-done for the moment</p>
<% else %>
    <ul>
        <% @todone.each do |t| %>
            <li>
                <%= link_to t.name, todo_path(t.id) %>
                <small><%= link_to "Remove", t, :confirm => "Is it ok to remove this item ?",:method => :delete %></small>
            </li>
        <% end %>
    </ul>
<% end %>

app/views/todo/new.html.erb
<h1>Add new item to your to-do list</h1>
<%= form_for @todo, :url => todo_index_path(@todo) do |f| %>
    <%= f.hidden_field :done, :value => false %>
    <div class="form-group">
      <p><%= f.label :name %></p>
      <p><%= f.text_field :name, :class => "form-control", :placeholder => "My to-do item" %></p>
    </div>
    <div class="form-group">
      <p><%= f.label :description %></p>
      <p><%= f.text_area :description, :class => "form-control", :placeholder => "Add a description", size:"50x10" %></p>
    </div>
    <div class="form-group">
        <%= f.submit "Add to-do element", :class => "btn btn-primary" %>
    </div>
<% end %>

app/views/todo/show.html.erb
<h1><%= @todo.name %></h1>
<p>
    <%= @todo.description %>
</p>